"""Add profile_pic 

Revision ID: cdcfe2ba14d4
Revises: c4e50445fe4c
Create Date: 2024-09-22 18:31:54.185878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcfe2ba14d4'
down_revision = 'c4e50445fe4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=500), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
